common/models/PageZoneSettings.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "page_zone_settings".
 *
 * @property int $id
 * @property string $page_section_name
 * @property string $page_name
 * @property string $page_zone_name
 * @property int $source_partner_id
 * @property int $items_number
 */
class PageZoneSettings extends \yii\db\ActiveRecord
{
    const SOURCE_PARTNER_ID_ALL = 0;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'page_zone_settings';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['page_section_name', 'page_name', 'page_zone_name', 'items_number'], 'required'],
            [['source_partner_id', 'items_number'], 'integer'],
            [['page_section_name', 'page_name', 'page_zone_name'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'page_section_name' => 'Page Section Name',
            'page_name' => 'Page Name',
            'page_zone_name' => 'Page Zone Name',
            'source_partner_id' => 'Source Partner ID',
            'items_number' => 'Items Number',
        ];
    }

    /**
     * @param string $pageSectionName
     * @param string $pageName
     * @param string $pageZoneName
     * @param int $sourcePartnerId
     * @return array|null|PageZoneSettings
     */
    public static function getBySectionAandPAgeAndZoneAndSourcePartnerId($pageSectionName, $pageName, $pageZoneName, $sourcePartnerId)
    {
        return self::find()
            ->where(['=', 'page_section_name', $pageSectionName])
            ->andWhere(['=', 'page_name', $pageName])
            ->andWhere(['=', 'page_zone_name', $pageZoneName])
            ->andWhere(['=', 'source_partner_id', $sourcePartnerId])
            ->one();
    }

    /**
     * @param string $pageSectionName
     * @param string $pageName
     * @param string $pageZoneName
     * @param int $sourcePartnerId
     * @return array|PageZoneSettings|null
     */
    public static function getPageZoneSettings($pageSectionName, $pageName, $pageZoneName, $sourcePartnerId)
    {
        $model = self::getBySectionAandPAgeAndZoneAndSourcePartnerId($pageSectionName, $pageName, $pageZoneName, $sourcePartnerId);

        if (!$model) {
            $model = self::getBySectionAandPAgeAndZoneAndSourcePartnerId($pageSectionName, $pageName, $pageZoneName, self::SOURCE_PARTNER_ID_ALL);
        }

        return $model;
    }
}

backend/controllers/PageZoneSettingsController.php
<?php

namespace backend\controllers;

use backend\models\PageZoneSettingsForm;
use backend\models\PageZoneSettingsSearchIndexForm;
use common\models\Feed;
use common\models\PageSection;
use common\models\PageZone;
use common\models\PageZoneFeedSort;
use common\models\PageZoneRuleGroup;
use common\models\PageZoneRuleWeekdayTime;
use common\models\Source;
use Yii;
use common\models\PageZoneSettings;
use common\models\PageZoneSettingsSearch;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * PageZoneSettingsController implements the CRUD actions for PageZoneSettings model.
 */
class PageZoneSettingsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all PageZoneSettings models.
     * @return mixed
     */
    public function actionIndex()
    {
        $pageZoneSettingsSearchIndexForm = new PageZoneSettingsSearchIndexForm();

        $data = Yii::$app->request->get();
        $data = isset($data['PageZoneSettingsSearchIndexForm']) ? $data['PageZoneSettingsSearchIndexForm'] : [];
        if (isset($data['week_day_time_data'])) {
            $data['week_day_time_data'] = json_decode($data['week_day_time_data']);
        }
        $pageZoneSettingsSearchIndexForm->setAttributes($data);

        $pageSectionActive = PageSection::getPageSectionByName($pageZoneSettingsSearchIndexForm->page_section_name);
        $pageActive = $pageZoneSettingsSearchIndexForm->page_name ? $pageSectionActive->getPageByName($pageZoneSettingsSearchIndexForm->page_name) : [];


        $query = PageZoneRuleGroup::find()->alias('pzrg')->leftJoin(['pzrwt' => PageZoneRuleWeekdayTime::tableName()], 'pzrwt.page_zone_rule_group_id = pzrg.id')->groupBy('pzrg.id');

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'forcePageParam' => false,
                'pageSizeParam' => false,
                'pageSize' => 20
            ]
        ]);


        if (!empty($pageZoneSettingsSearchIndexForm->rule_group_id)) {
            $query->andFilterWhere([
                'pzrg.id' => $pageZoneSettingsSearchIndexForm->rule_group_id
            ]);
        } else {
            if (!empty($pageZoneSettingsSearchIndexForm->page_section_name)) {
                $query->andFilterWhere([
                    'pzrg.page_section_name' => $pageZoneSettingsSearchIndexForm->page_section_name
                ]);
            }

            if (!empty($pageZoneSettingsSearchIndexForm->page_name)) {
                $query->andFilterWhere([
                    'pzrg.page_name' => $pageZoneSettingsSearchIndexForm->page_name
                ]);
            }

            if (!empty($pageZoneSettingsSearchIndexForm->page_zone_name)) {
                $query->andFilterWhere([
                    'pzrg.page_zone_name' => $pageZoneSettingsSearchIndexForm->page_zone_name
                ]);
            }

            if ($pageZoneSettingsSearchIndexForm->source_partner_id != '') {
                $query->andFilterWhere([
                    'pzrg.source_partner_id' => $pageZoneSettingsSearchIndexForm->source_partner_id
                ]);
            }

            if (!empty($pageZoneSettingsSearchIndexForm->inbound_keyword)) {
                $query->andFilterWhere([
                    'like',
                    'pzrg.inbound_keyword',
                    $pageZoneSettingsSearchIndexForm->inbound_keyword
                ]);
            }

            $activeHoursWeekDay = PageZoneRuleWeekdayTime::getActiveHoursWeekDay($pageZoneSettingsSearchIndexForm->week_day_time_data);
            if (!count($activeHoursWeekDay)) {
                $query->andFilterWhere(['pzrg.id' => 0]);
            } else {
                $weekDayHoursConflictCondition = [];
                $weekDayHoursConflictCondition[] = 'OR';
                foreach ($activeHoursWeekDay as $day => $hours) {
                    $weekDayHoursConflictCondition[] = [
                        'AND',
                        ['=', 'pzrwt.week_day', $day],
                        ['IN', 'pzrwt.hour', $hours]
                    ];
                }

                $query->andFilterWhere($weekDayHoursConflictCondition);
            }
        }

        return $this->render('index', [
            'searchFormModel' => $pageZoneSettingsSearchIndexForm,
            'pageSections' => PageSection::getAll(),
            'pages' => $pageSectionActive ? $pageSectionActive->pages : [],
            'pageZones' => $pageActive ? $pageActive->zones : [],
            'sources' => Source::getAll(),
            'dataProvider' => $dataProvider
        ]);
    }

    /**
     * Creates a new PageZoneSettings model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $pageZoneSettingsForm = new PageZoneSettingsForm();

        return $this->render('create-new', [
            'model' => $pageZoneSettingsForm,
            'pageSections' => PageSection::getAll(),
            'itemsCountLimit' => 12,
            'pageZoneFeedSorts' => PageZoneFeedSort::getAll(),
            'feeds' => Feed::getAll(),
            'sources' => Source::getAll(),
        ]);
    }

    /**
     * Updates an existing PageZoneSettings model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        if (Yii::$app->request->isAjax) {
            $pageZoneSettingsForm = new PageZoneSettingsForm();

            $data = Yii::$app->request->post();

            $pageZoneSettingsForm->setAttributes($data);
            try {
                $pageZoneSettingsForm->save();
            } catch (\Exception $e) {
                $pageZoneSettingsForm->addError('rule_group_id', $e->getMessage());
            }

            if (empty($pageZoneSettingsForm->getErrors())) {
                return $this->asJson([
                    'status' => 'success'
                ]);
            } else {
                $message = '';
                foreach ($pageZoneSettingsForm->getErrors() as $attributeName => $error) {
                    $message .= implode(', ', $error) . "\n";
                }

                return $this->asJson([
                    'status' => 'error',
                    'message' => $message
                ]);
            }
        }

        $pageZoneSettingsForm = PageZoneSettingsForm::findByRuleGroupId($id);

        $pageSectionActive = PageSection::getPageSectionByName($pageZoneSettingsForm->page_section_name);
        $pageActive = $pageSectionActive->getPageByName($pageZoneSettingsForm->page_name);

        return $this->render('update-new', [
            'model' => $pageZoneSettingsForm,
            'pageSections' => PageSection::getAll(),
            'pages' => $pageSectionActive->pages,
            'pageZones' => $pageActive->zones,
            'sources' => Source::getAll(),
            'itemsCountLimit' => 12,
            'pageZoneFeedSorts' => PageZoneFeedSort::getAll(),
            'feeds' => Feed::getAll()
        ]);
    }

    /**
     * Deletes an existing PageZoneSettings model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the PageZoneSettings model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return PageZoneRuleGroup the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = PageZoneRuleGroup::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    /**
     * @param string $pageSectionName
     * @return \yii\web\Response
     */
    public function actionPageList($pageSectionName)
    {
        $pageList = [];
        if (!empty($pageSectionName)) {
            $pageSection = PageSection::getPageSectionByName($pageSectionName);
            $pages = $pageSection->pages;
            foreach ($pages as $page) {
                $pageList[] = [
                    'name' => $page->name
                ];
            }
        }

        return $this->asJson([
            'pageList' => $pageList
        ]);
    }

    /**
     * @param string $pageSectionName
     * @param string $pageName
     * @return \yii\web\Response
     */
    public function actionPageZoneList($pageSectionName, $pageName)
    {
        $pageZoneList = [];

        if (!empty($pageSectionName) && !empty($pageName)) {
            $pageSection = PageSection::getPageSectionByName($pageSectionName);
            $page = $pageSection->getPageByName($pageName);

            $zones = $page->zones;
            foreach ($zones as $zone) {
                $pageZoneList[] = [
                    'name' => $zone->name

backend/views/page-zone-settings/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\PageZoneSettingsSearch */
/* @var $formModel \backend\models\PageZoneSettingsSearchIndexForm*/
/** @var \common\models\PageSection[] $pageSections */
/** @var \common\models\Page[] $pages */
/** @var \common\models\PageZone[] $pageZones */
/** @var \common\models\Source[] $sources */

?>

<div class="page-zone-settings-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'id' => 'filter-form'
    ]); ?>

    <?= $form->field($formModel, 'rule_group_id')->hint('If a value is specified in this field (rule_group_id), then the remaining filters will be ignored.') ?>

    <?php
    $pageSectionsList = \yii\helpers\ArrayHelper::map($pageSections, 'name', 'name');
    ?>
    <?= $form->field($formModel, 'page_section_name')->dropDownList($pageSectionsList, ['prompt' => '-- Select page section name --']) ?>

    <?php
    $pagesList = $pages ? \yii\helpers\ArrayHelper::map($pages, 'name', 'name') : [];
    ?>
    <?= $form->field($formModel, 'page_name')->dropDownList($pagesList, ['prompt' => '-- Select page --']) ?>

    <?php
    $pageZonesList = $pageZones ? \yii\helpers\ArrayHelper::map($pageZones, 'name', 'name') : [];
    ?>
    <?= $form->field($formModel, 'page_zone_name')->dropDownList($pageZonesList, ['prompt' => '-- Select page zone --']) ?>

    <?php
    $sourcesList = [];
    $sourcesList[0] = 'All sources';
    $sourcesList = $sourcesList + \yii\helpers\ArrayHelper::map($sources, 'id', 'name');
    ?>
    <?= $form->field($formModel, 'source_partner_id')->dropDownList($sourcesList, ['prompt' => '-- Select source partner --']) ?>

    <?= $form->field($formModel, 'inbound_keyword') ?>

    <div class="form-group field-pagezonesettingssearchindexform-weekdaytime required" style="overflow: auto;">
        <label class="control-label" for="pagezonesettingssearchindexform-weekdaytime">Week Day Time</label>

        <table class="J_timedSheet_table">
            <thead></thead>
            <tbody id="J_timedSheet">

            </tbody>
        </table>

        <div class="help-block"></div>
    </div>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Reset', '', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

<script>
    //(function() {
    var BlockFilter = function () {
        this.container = document.querySelector('.page-zone-settings-search');
        this.pageSectionNameSelect = this.container.querySelector('#pagezonesettingssearchindexform-page_section_name');
        this.pageNameSelect = this.container.querySelector('#pagezonesettingssearchindexform-page_name');
        this.pageZoneNameSelect = this.container.querySelector('#pagezonesettingssearchindexform-page_zone_name');
        this.weekDayTimeTable = null;
    };

    BlockFilter.prototype = {
        init: function () {
            if (!this.pageSectionNameSelect.value) {
                clearSelect(this.pageNameSelect, '-- Select page section first! --');
            }

            if (!this.pageNameSelect.value) {
                clearSelect(this.pageZoneNameSelect, '-- Select page first! --');
            }

            this.addPageNameSelectListenerChange();
            this.addPageSectionNameSelectListenerChange();
            this.createWeekDayTimeTable();
        },

        addPageSectionNameSelectListenerChange: function() {
            var self = this;

            this.pageSectionNameSelect.addEventListener('change', function(){
                clearSelect(self.pageNameSelect, '-- Select page section first! --');
                clearSelect(self.pageZoneNameSelect, '-- Select page first! --');

                var url = '<?= \yii\helpers\Url::toRoute(['page-zone-settings/page-list'], true) ?>';
                url += '?pageSectionName=' + self.pageSectionNameSelect.options[self.pageSectionNameSelect.selectedIndex].value;

                var xmlhttp = new XMLHttpRequest();
                xmlhttp.open("GET", url, true);
                xmlhttp.send();

                xmlhttp.onreadystatechange = function() {
                    if (xmlhttp.readyState !== 4) return;

                    var response = JSON.parse(xmlhttp.responseText);
                    if (response.pageList && response.pageList.length > 0) {
                        var options = [];
                        response.pageList.forEach(function (item, key) {
                            var option = {
                                'label': item.name,
                                'value': item.name
                            };
                            options.push(option)
                        });

                        fillSelect(self.pageNameSelect, options, '-- Select page --');
                    }
                }
            });
        },

        addPageNameSelectListenerChange: function() {
            var self = this;

            this.pageNameSelect.addEventListener('change', function(){
                clearSelect(self.pageZoneNameSelect, '-- Select page first! --');

                var url = '<?= \yii\helpers\Url::toRoute(['page-zone-settings/page-zone-list'], true) ?>';
                url += '?pageSectionName=' + self.pageSectionNameSelect.options[self.pageSectionNameSelect.selectedIndex].value;
                url += '&pageName=' + self.pageNameSelect.options[self.pageNameSelect.selectedIndex].value;

                var xmlhttp = new XMLHttpRequest();
                xmlhttp.open("GET", url, true);
                xmlhttp.send();

                xmlhttp.onreadystatechange = function() {
                    if (xmlhttp.readyState !== 4) return;

                    var response = JSON.parse(xmlhttp.responseText);
                    if (response.pageZoneList && response.pageZoneList.length > 0) {
                        var options = [];
                        response.pageZoneList.forEach(function (item, key) {
                            var option = {
                                'label': item.name,
                                'value': item.name
                            };
                            options.push(option)
                        });

                        fillSelect(self.pageZoneNameSelect, options, '-- Select page zone --');
                    }
                }
            });
        },

        createWeekDayTimeTable: function () {
            var self = this;

            var dayList = [
                {name: "Monday"},
                {name: "Tuesday"},
                {name: "Wednesday"},
                {name: "Thursday"},
                {name: "Friday"},
                {name: "Saturday"},
                {name: "Sunday"}
            ];

            var hourList = [
                {name:"00",title:"00:00-01:00"},{name:"01",title:"01:00-02:00"},{name:"02",title:"02:00-03:00"},{name:"03",title:"03:00-04:00"},
                {name:"04",title:"04:00-05:00"},{name:"05",title:"05:00-06:00"},{name:"06",title:"06:00-07:00"},{name:"07",title:"07:00-08:00"},
                {name:"08",title:"08:00-09:00"},{name:"09",title:"09:00-10:00"},{name:"10",title:"10:00-11:00"},{name:"11",title:"11:00-12:00"},
                {name:"12",title:"12:00-13:00"},{name:"13",title:"13:00-14:00"},{name:"14",title:"14:00-15:00"},{name:"15",title:"15:00-16:00"},
                {name:"16",title:"16:00-17:00"},{name:"17",title:"17:00-18:00"},{name:"18",title:"18:00-19:00"},{name:"19",title:"19:00-20:00"},
                {name:"20",title:"20:00-21:00"},{name:"21",title:"21:00-22:00"},{name:"22",title:"22:00-23:00"},{name:"23",title:"23:00-24:00"}
            ];

            var dimensions = [dayList.length, hourList.length];

            var sheetData = JSON.parse('<?= json_encode($formModel->week_day_time_data) ?>');

            var updateRemark = function(sheet){

                var sheetStates = sheet.getSheetStates();
                var rowsCount = dimensions[0];
                var colsCount = dimensions[1];
                var rowRemark = [];
                var rowRemarkLen = 0;
                var remarkHTML = '';

                for(var row= 0, rowStates=[]; row<rowsCount; ++row){
                    rowRemark = [];
                    rowStates = sheetStates[row];
                    for(var col=0; col<colsCount; ++col){
                        if (rowStates[col]===0 && rowStates[col-1]===1) {
                            rowRemark[rowRemarkLen-1] += (col<=10?'0':'')+col+':00';
                        } else if(rowStates[col]===1 && (rowStates[col-1]===0 || rowStates[col-1]===undefined)) {
                            rowRemarkLen = rowRemark.push((col<=10?'0':'')+col+':00-');
                        }

                        if (rowStates[col]===1 && col===colsCount-1) {
                            rowRemark[rowRemarkLen-1] += '24:00';
                        }
                    }
                    remarkHTML = rowRemark.join("，");
                    sheet.setRemark(row,remarkHTML==='' ? sheet.getDefaultRemark() : remarkHTML);
                }
            };

            $(document).ready(function(){
                self.weekDayTimeTable = $("#J_timedSheet").TimeSheet({
                    data: {
                        dimensions : dimensions,
                        colHead : hourList,
                        rowHead : dayList,
                        sheetHead : {name:"Week Day\\Time"},
                        sheetData : sheetData
                    },
                    remarks : {
                        title : "Description",
                        default : "N/A"
                    },
                    end : function(ev,selectedArea){
                        updateRemark(self.weekDayTimeTable);
                    }
                });

                updateRemark(self.weekDayTimeTable);
            });
        }
    };

    var BlockController = function () {
        this.blocks = {
            filter:   new BlockFilter()
        };
    };

    BlockController.prototype = {
        init: function () {
            this.initBlocks();
        },

        initBlocks: function () {
            for (var blockName in this.blocks) {
                if (this.blocks.hasOwnProperty(blockName)) {
                    var block = this.blocks[blockName];

                    if (typeof block.init === 'function') {
                        block.init();
                    }
                }
            }
        }
    };

    var blockController = null;
    document.addEventListener('DOMContentLoaded', function(){
        blockController = new BlockController();
        blockController.init();

        $('#filter-form').submit(function(e) {
            $(this).find('.week_day_time_data_input').remove();

            var sheetStates = blockController.blocks.filter.weekDayTimeTable.getSheetStates();

            $('<input />').attr('type', 'hidden')
                .attr('name', "PageZoneSettingsSearchIndexForm[week_day_time_data]")
                .attr('class', 'week_day_time_data_input')
                .attr('value', JSON.stringify(sheetStates))
                .appendTo(this);

            return true;
        });
    });


    //})();
</script>

backend/views/page-zone-settings/create-new.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/** @var \backend\models\PageZoneSettingsForm $model */
/** @var \common\models\PageSection[] $pageSections */
/** @var int $itemsCountLimit */
/** @var \common\models\PageZoneFeedSort[] $pageZoneFeedSorts */
/** @var \common\models\Feed[] $feeds */
/** @var \common\models\Source[] $sources */

$this->title = 'Create Page Zone Settings';

?>
<div class="page-zone-settings-create">
    <?= $this->render('_form', [
        'model' => $model,
        'pageSections' => $pageSections,
        'pages' => [],
        'pageZones' => [],
        'itemsCountLimit' => $itemsCountLimit,
        'pageZoneFeedSorts' => $pageZoneFeedSorts,
        'feeds' => $feeds,
        'sources' => $sources
    ]) ?>
</div>

backend/views/page-zone-settings/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\PageZoneSettings */
/** @var \common\models\PageSection[] $pageSections */
/** @var \common\models\Source[] $sources */

$this->title = 'Create Page Zone Settings';
$this->params['breadcrumbs'][] = ['label' => 'Page Zone Settings', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="page-zone-settings-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'pageSections' => $pageSections,
        'sources' => $sources
    ]) ?>

</div>

backend/views/page-zone-settings/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this \frontend\components\View */
/** @var \backend\models\PageZoneSettingsSearchIndexForm $searchFormModel */
/** @var \common\models\PageSection[] $pageSections */
/** @var \common\models\Page[] $pages */
/** @var \common\models\PageZone[] $pageZones */
/** @var \common\models\Source[] $sources */

$this->title = 'Page Zone Settings';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="page-zone-settings-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Page settings rule', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= $this->render('_search', [
        'formModel' => $searchFormModel,
        'pageSections' => $pageSections,
        'pages' => $pages,
        'pageZones' => $pageZones,
        'sources' => $sources
    ]) ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [

            'id',
            'page_section_name',
            'page_name',
            'page_zone_name',
            [
                'label' => 'Source Partner',
                'value' => function (\common\models\PageZoneRuleGroup $model) {
                    if ($model->source) {
                        return $model->source->name;
                    }

                    return 'All partners';
                }
            ],
            'inbound_keyword',
            /*'campaign',
            'adgroup',
            'category',
            'keyword',
            'key',
            'url:url',
            [
                'label' => 'Final url',
                'value' => function (\common\models\Link $model) {
                    return $model->getFinalUrl();
                }
            ],*/

            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{update} {delete}'
            ],
        ],
    ]); ?>

</div>

backend/views/page-zone-settings/update-new.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/** @var \backend\models\PageZoneSettingsForm $model */
/** @var \common\models\PageSection[] $pageSections */
/** @var \common\models\Page[] $pages */
/** @var \common\models\PageZone[] $pageZones */
/** @var int $itemsCountLimit */
/** @var \common\models\PageZoneFeedSort[] $pageZoneFeedSorts */
/** @var \common\models\Feed[] $feeds */
/** @var \common\models\Source[] $sources */

$this->title = 'Create Page Zone Settings';

?>
<div class="page-zone-settings-create">
    <?= $this->render('_form', [
        'model' => $model,
        'pageSections' => $pageSections,
        'pages' => $pages,
        'pageZones' => $pageZones,
        'itemsCountLimit' => $itemsCountLimit,
        'pageZoneFeedSorts' => $pageZoneFeedSorts,
        'feeds' => $feeds,
        'sources' => $sources
    ]) ?>
</div>

backend/views/page-zone-settings/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\PageZoneSettings */

$this->title = 'Update Page Zone Settings: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Page Zone Settings', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="page-zone-settings-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/page-zone-settings/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\PageZoneSettings */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Page Zone Settings', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="page-zone-settings-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'page_section_name',
            'page_name',
            'page_zone_name',
            'source_partner_id',
            'items_number',
        ],
    ]) ?>

</div>